spring:
  resources:
    static-locations: classpath:/static/src/html/
  mvc:
    static-path-pattern: //**
##################### DB #####################
  datasource:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/zhiyuan?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
            username: root
            password: CEE9246
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT user()
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
#mybatis配置
mybatis:
  mapper-locations: classpath:com/dao/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.model  # 注意：对应实体类的路径
server:
  port: 8088


#pageHelper配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

